# Generated by Django 2.2.3 on 2019-07-29 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='player_y',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_y', to=settings.AUTH_USER_MODEL),
        ),
    ]
