# Generated by Django 2.2.3 on 2019-07-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
