# Generated by Django 2.2.3 on 2019-07-19 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nm', '0002_auto_20190719_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
